### ISSUE TITLE
[CC API] OAuth: CCID? Other?

### ISSUE THREAD

**Issue by pa-w** [creativecommons/cccatalog-api#2]
This API will have clients which will need consumer keys and secrets (OAuth)...

Let's implement OAuth and see if we can use CCID for these purposes.

**Comment by pa-w** [comment]
Using GitHub users can work pretty well, also.

@aldenstpage, what do you think?

**Comment by aldenstpage** [comment]
I like the suggestion to use GitHub accounts. I don't want to link it up to CCID since it sounds like nobody wants to maintain it and because API authorization should be managed separately from application authorization.

**Comment by aldenstpage** [comment]
I added support for two OAuth2 authorization flows:
1) For push API users: We issue a `client id` and `client secret` to whoever wants access to our API. Using those details, they request a temporary bearer token from our API server. There is no third party for this flow; everything happens on our servers.
2) GitHub social login for front-end users. We should support more options later, since most end users will not be developers. It is relatively easy to add a new social backend as long as it's supported by [python-social-auth](http://python-social-auth.readthedocs.io/en/latest/backends/index.html).
