### ISSUE TITLE
Implement browse by collection/provider

### ISSUE THREAD

**Issue by aldenstpage** [creativecommons/cccatalog-api#205]
Implement endpoint for browsing by collection, e.g. `/{provider_name}?page=2&pagesize=20`.

**Comment by janeatcc** [comment]
We didn't actually decide this yet, did we? Given our API strategy...

**Comment by aldenstpage** [comment]
It's in the list of items we committed to in the sprint. Like the search end point, it will be rate limited to prevent abuse. We can also expose just the first 10,000 works through this API to prevent copying everything. That way, users can still browse to their heart's content (barely anybody/nobody needs more than 100 pages of results) without effectively providing a dump of the entire database through this endpoint.

**Comment by janeatcc** [comment]
Ok I like the idea of employing both. 

The rate limit would be a technical limit, as would be exposing only the first 10,000 works. Since we're exposing that through our own use of the API, though, the TOS on the API might not cover the end user. Is that a correct reading?

cc: @sarahpearson -- let's discuss which terms (API or general on CC search) would cover this

**Comment by kgodey** [comment]
this discussion was moved to Slack, we'll post an update here once we decide on a course of action.

**Comment by janeatcc** [comment]
let's take this off active sprint. there are additional reasons not to do this that we need to discuss.

**Comment by janeatcc** [comment]
Confirming this can go ahead, but as a feature for post-summit, and pending final review by myself and Sarah.
