### ISSUE TITLE
License tags should probably be filtered out or be a special category

### ISSUE THREAD

**Issue by mzeinstra** [creativecommons/cccatalog-api#253]
When you find an image (https://ccsearch.creativecommons.org/photos/16136571 for example) and what to explore further using the tags there should be a special category or filtering of all common names of CC licenses.

When you click on a tag for, example CC0, you expect to find more cc0 material. However that tag also appears on non cc0 licensed material. This is confusion to the end-user.

**Comment by aldenstpage** [comment]
Thanks! We have a tag blacklist now, so we'll be able to eliminate these tags.

**Comment by mzeinstra** [comment]
The is not live yet I presume? Otherwise the issue is not resolved yet. See first result.

![image](https://user-images.githubusercontent.com/5627431/56436101-099aa380-62db-11e9-87d8-df045db23be1.png)

**Comment by aldenstpage** [comment]
A handful of works seem to have retained the CC0 tag, which is strange (there are ~36,000 fewer results now, at least). Some of the results also have "CC0" in the title, which is a problem because we cannot alter the title of a work. We could change the search index to filter out the title, but this will require making a new field (we need to preserve the original unaltered title in the search results, even if behind the scenes we are excluding parts of it from search).

I reopened this so we can look into a better solution.

**Comment by janeatcc** [comment]
I don't think we should be altering the title on the front end either, per our discussion today, fyi.

**Comment by annatuma** [comment]
@aldenstpage this is on your plate for the next sprint. We're starting this in "ticket work required", because a thorough review of the discussion, and an update to the description, should happen before work on this starts. Move to the appropriate pipeline once that is done.

**Comment by aldenstpage** [comment]
We're filtering out these tags properly now. Of course, if a license shows up in the description or title field, it will still show up; users should use license filters instead to avoid that
