### ISSUE TITLE
The image search API returns one less image per page given the pagesize

### ISSUE THREAD

**Issue by dhruvkb** [creativecommons/cccatalog-api#256]
**Describe the bug**
The image search view returns n-1 images when the query parameters include `pagesize=n`. This has been tested at

```
https://api-dev.creativecommons.engineering/image/search/?q=bird&pagesize={n}
```

**Expected behavior**
For `pagesize=n`, n images should be returned.

**Comment by ahmedkrmn** [comment]
I've also noticed this weird behavior though it's not consistent. 
Sometimes in returns the exact `pagesize` as requested and sometimes it returns `n-1` pages as you say.

**Comment by dhruvkb** [comment]
I tried to examine the view that performs the slicing and [the code written there](https://github.com/creativecommons/cccatalog-api/blob/274770a744c240e52c812650dd525a14798c6319/cccatalog-api/cccatalog/api/controllers/search_controller.py#L35) seems perfectly alright!

```python
start_slice = page_size * (page - 1)
end_slice = page_size * page
if start_slice + end_slice > ELASTICSEARCH_MAX_RESULT_WINDOW:
    raise ValueError("Deep pagination is not allowed.")
s = s[start_slice:end_slice]
```

**Comment by aldenstpage** [comment]
It's because we filter out broken links in the results. If you add `&filter_dead=False` to your query, you'll end up with the expected number of images. See #314.

In addition to having a process for clearing out a lot of the link rot, someone is working on addressing this issue. https://github.com/creativecommons/cccatalog-api/pull/358/
