### ISSUE TITLE
Implement endpoint for processing bug reports from end users

### ISSUE THREAD

**Issue by aldenstpage** [creativecommons/cccatalog-api#264]
![Example request](https://i.imgur.com/QuXuklk.png)

Bugs should be forwarded to GitHub issues with a triage tag.

**Comment by Sando1** [comment]
Hi @aldenstpage! I would like to work on this.

**Comment by DantrazTrev** [comment]
Hi @aldenstpage is this still open for work
?

**Comment by krysal** [comment]
Hi @aldenstpage @annatuma 👋 Is this task different from [this](https://github.com/creativecommons/cccatalog-api/issues/474) other? If so I can work on this.

**Comment by SaurabhAgarwala** [comment]
@aldenstpage I would like to work on this issue. Please assign it to me.

**Comment by krysal** [comment]
@SaurabhAgarwala CC Staff is no longer assigning people to issues, you can start right away if you want, I wanted to work on this but was wondering is the endpoint is indeed still needed.

**Comment by SaurabhAgarwala** [comment]
Hey @krysal, I think we are free to submit a PR without being assigned only those issues marked `help wanted`. For others, I believe we need permission. 
Yeah, even I was wondering if this endpoint is still needed and hence asked for permission.
If this endpoint is still needed, since you asked before, so you can work on it alone or if you want we can work collaboratively as well.
