### ISSUE TITLE
Move automated tests from Travis CI to GitHub Actions

### ISSUE THREAD

**Issue by kgodey** [creativecommons/cccatalog-api#265]
Per the decision in a previous engineering meeting.

**Comment by dhruvkb** [comment]
I'd like to take this up, given some prior experience in this area (see creativecommons/cccatalog-frontend#294 solving creativecommons/cccatalog-frontend#283 :grin:).

However, the backend tests are significantly more complex compared to the frontend tests, so it'd be a nice challenge.

**Comment by kgodey** [comment]
Go ahead!

**Comment by dhruvkb** [comment]
So far I have managed to run linter tests to run on CircleCI using this [configuration file](https://github.com/dhruvkb/cccatalog-api/blob/6da7bfdd808deee45f26b82990a9c28a13db7ff6/.circleci/config.yml).
![image](https://user-images.githubusercontent.com/16580576/56470199-0c270580-6461-11e9-91dc-3a8e8e667517.png)

I am facing a dillemma on how to go about testing the actual services because the test scripts have been written using Docker from a `machine` standpoint whereas CircleCI offers a more containerised, faster experience with the `docker` executor. Comparisons [provided](https://circleci.com/docs/2.0/executor-types/#section=configuration).

While the executor `machine` will provide a very Travis-like experience, including very little reworking in the test scripts such as `load_sample_data.sh`, it is slow and may become priced in a future update. Rewriting the scripts for CircleCI would mean Travis tests will break.

Should I rework the scripts for CircleCI `docker` or go with the `machine` executor?

**Comment by kgodey** [comment]
I'll defer to @aldenstpage

**Comment by aldenstpage** [comment]
I did some research, and I think it will be quite cumbersome to port this with the `docker` executor. We are essentially running our integration test against a live instance of CC Search, which means our tests need access to low-level tools to detect when the system has fully started and to ingest and index sample image records. I believe preserving the existing setup in `machine` will provide the best results; we want to be able to detect failures before we ship to production, and integration tests do a pretty good job of that. Overhauling the tests to be more traditional bite-sized unit tests would be a lot of work and maybe a step backwards in terms of actual coverage.

I expect we won't exhaust the 1000 minutes of free execution time, and the 30-60 seconds of `machine` startup time isn't a dealbreaker (Travis takes much longer).

**Comment by dhruvkb** [comment]
Okay @aldenstpage, I'll write the tests using the `machine` executor.

**Comment by aldenstpage** [comment]
There's some activity on this issue here, but it needs some more work: https://github.com/creativecommons/cccatalog-api/pull/278

**Comment by AyanChoudhary** [comment]
Can I work on this PR?

**Comment by aldenstpage** [comment]
Yes, please do. We've decided to go with GitHub actions instead of CircleCI, however.

**Comment by aldenstpage** [comment]
@annatuma @kgodey Let's try to get this and https://github.com/creativecommons/cccatalog-api/issues/369 in the next sprint; these issues are bogging down API development.
