### ISSUE TITLE
search for relevant key terms under mccord museum returns no results

### ISSUE THREAD

**Issue by janeatcc** [creativecommons/cccatalog-api#274]
e.g. see http://collections.musee-mccord.qc.ca/en/collection/artifacts/M977.51

I search for "red lake" which should return something but it doesn't https://ccsearch.creativecommons.org/search?q=red%20lake&provider=mccordmuseum&li=&lt=&searchBy

**Comment by aldenstpage** [comment]
This issue is a little bit different than the other recent bugs you filed. There are two problems:
1) McCord does not support HTTPS.
2) McCord thumbnails do not have any protocol in the URL. See [here](http://api.creativecommons.engineering/image/search?q=natural%20history&provider=museumsvictoria&filter_dead=False) examples.
3) When protocols are missing, we presume HTTPS is supported and append it. But McCord doesn't support HTTPS, so adding HTTPS will break the links. If `http://` appears in the thumbnail URL, however, we will proxy the image, and it will work fine.

IMO, the best way to fix this is to specify the protocol in the upstream database for McCord thumbnails in particular, to ensure consistency in how we handle thumbnails. Testing both the HTTP and HTTPS versions of the link is not an option because it will double the number of requests we make to this provider. We cannot assume the protocol because of 3). What do you think, @sclachar?

**Comment by kgodey** [comment]
I assume by "upstream database" you mean the catalog database (and not the API database). I'm wary of transforming data in the catalog database since we're only supposed to be storing data that we get directly from providers but I don't think it would cause any harm to do so in the case.

I think the better solution might be to default to `http://` when no protocol is specified because that will always work and we're fetching public data anyway so it doesn't matter as much if it's encrypted. Maybe we could store a mapping of which providers support HTTP and which ones support HTTPS so that we use HTTPS whenever possible. It seems like it would be possible to automatically generate those settings during the ingestion job by testing a random sample of the provider's URLs using both HTTP and HTTPS.

Overall, I don't have a strong opinion on this.

**Comment by sclachar** [comment]
@kgodey the mappings can be inferred from the content provider table

**Comment by aldenstpage** [comment]
This is fixed now, see these [search results](https://ccsearch.creativecommons.org/search?q=red%20lake&provider=mccordmuseum&li=&lt=&searchBy).
