### ISSUE TITLE
Evaluate Wasabi and Sixpack to use for running A/B tests

### ISSUE THREAD

**Issue by kgodey** [creativecommons/cccatalog-api#320]
[Sixpack](https://github.com/sixpack/sixpack) and [Wasabi](https://github.com/intuit/wasabi) are API-driven A/B testing frameworks that should work for both frontend and API tests, as well as tests combining the two.

Evaluate both options for the following use cases:
- A combined frontend/backend experiment that allows the backend to send different search algorithms to each other and the frontend measures the user rating of their search results (this may be able to be run entirely on the backend if the frontend sends the user ratings to the backend)
- A frontend only experiment to test different designs of the same feature

Evaluate ease of use, ease of checking results, ease of setting up new experiments, etc.

Expected output is either a recommendation for which framework to use or feedback on what to look for in a new tool.

**Comment by aldenstpage** [comment]
@kgodey @brenoferreira Having spent some time setting up both projects and doing some basic testing, my vote goes to Sixpack for being simpler to operate and having more or less the same feature set (but, in my opinion, a better UI than Wasabi).

Would it be helpful if I set up Sixpack in the test development environment?

**Comment by kgodey** [comment]
My only other question is whether Sixpack has all the features you'd want from an A/B testing tool (for example, when conducting an experiment with two different search algorithm and comparing user behavior via [usage data](https://github.com/creativecommons/cccatalog-frontend/issues/426). We can evaluate commercial options or other frameworks if there's something major missing. If you're happy with Sixpack, I think setting it up in a test environment is a great next step.

**Comment by aldenstpage** [comment]
>My only other question is whether Sixpack has all the features you'd want from an A/B testing tool (for example, when conducting an experiment with two different search algorithm and comparing changes in usage data)

Sixpack is able to count either conversions or basic KPIs for each experiment, like "number of times the attribution button was clicked in experiment A vs B vs C", or "number of times the user performed an additional search in experiment A vs B". The problem is that we want to track a lot more than just clicks and views over time.

I don't think it will be possible to capture the richer search metrics you want to track in Sixpack or Wasabi, particularly those related to specific search queries and images. In addition to inability to do anything besides count KPIs/impressions, we are going to have a huge amount of experiments since we want search and image level granularity, and having tens of thousands of experiments will most likely stretch the capability of these tools. Perhaps there is a commercial package with these capabilities; I personally don't know of any that I can recommend. We could use Sixpack if we scale back the scope of analytics to button clicks and page views.

If the goal is to tie all analytics to A/B tests, I suggest that we add an optional `experiment_name` parameter to all analytics API calls, pass the `experiment_name` to the cccatalog API somehow, and eschew A/B testing frameworks entirely. The server and frontend can modify their behavior based on the assigned experiment name. 

From there, we can create reports by pulling data from analytics DB and plotting them with `matplotlib` or similar (we could run the scripts on demand from our laptops, set up a cronjob somewhere on the internal network, whatever; there will be some lightweight way to visualize this data without building a web UI).

**Comment by kgodey** [comment]
Sorry for being unclear; I think we should only have one or two KPIs that we track for each A/B test experiment and to only be running one or two experiments at any given time. I don't think it is a good idea to run A/B experiments per search term or search result, we're not going to get any useful or statistically significant data out of that.

Examples of what I do want to be able to do:
* Set up an A/B test on two different search algorithms that uses the following KPIs:
    * the average star rating for search relevance across all search terms
    * the amount that a user scrolled before clicking the first result across all search terms
* Set up an A/B test on two different designs for a new filter on the search results page with the KPI of how many times the filter was clicked on/used by all users who saw each variant

These KPIs are a subset of the usage data so I wanted to see we could reuse that data in Sixpack rather than having to send the data to the analytics backend as well as Sixpack separately.

I think the bulk of the analytics would not be tied to A/B testing in any way, it's just data for us to see how usage of the site is changing over time and to (1) identify search terms with low quality results, and (2) identify high quality content based on usage.

**Comment by aldenstpage** [comment]
Ah, OK. We could have a KPI for `search-rated` and `user-scrolled`. A high rating can be treated as a conversion. Same for a low scroll distance.

For the second example, we could have a `filter-design` experiment and treat clicks on the new filter as a conversion. (it's a toy example, I doubt we want to incentivize using some filters over others)

**Comment by aldenstpage** [comment]
@kgodey @brenoferreira Sixpack is up and running in our development environment. Some information for getting started:

- The best documentation for using the Sixpack backend API is located [here](https://github.com/sixpack/sixpack).
- The Sixpack UI is accessible at https://sixpack.creativecommons.engineering (this will be secured before we go to production)
- Our sixpack API instance can be reached at https://api-dev.creativecommons.engineering/sixpack/.
- You can use `sixpack-js` to make the frontend behave differently for users participating in A/B tests.

**Comment by kgodey** [comment]
Closing this issue because we decided on Sixpack.
