### ISSUE TITLE
Speed up data cleaning and search indexing process

### ISSUE THREAD

**Issue by kgodey** [creativecommons/cccatalog-api#321]
Data cleaning and indexing speed is becoming a barrier to iterating on the search algorithm. We should split the ingestion server into a bunch of workers.

Ideas discussed:
- Nomad cluster on AWS EC2 (note: running a cluster might be too much operational overhead)
- AWS ECS
- AWS EKS
- AWS SQS / Lambda (note: task may be too intensive for Lambda)
- Celery on AWS Elastic Beanstalk workers

@aldenstpage please add more details as necessary

**Comment by aldenstpage** [comment]
The ingestion process is in need of a redesign, as it was conceived before we planned to implement a data standardization step. Rather than doing huge amounts of database IO on individual rows, we should dump the upstream database to a CSV, clean the data up, and only then load it into the upstream database. This should be doable in a reasonable period of time with one node.

The indexing step can be parallelized among multiple workers as we discussed.

**Comment by aldenstpage** [comment]
The indexing step is parallelized now, but the cleanup step has not been changed. Rather than switching to CSV processing (which is not as fast as I'd hoped), I think it would be worthwhile to parallelize it across the indexing workers in a similar manner.

This issue is succeeded by https://github.com/creativecommons/cccatalog-api/issues/380
