### ISSUE TITLE
Plan out architecture for serving thumbnails

### ISSUE THREAD

**Issue by annatuma** [creativecommons/cccatalog-api#398]
Part of the AWS Imagine Grant.

**Comment by datbossg310** [comment]
Thanks

**Comment by datbossg310** [comment]
Can i have my assets and money back.

**Comment by aldenstpage** [comment]
Just to be clear, I'm going to focus on exclusively on serving thumbnails (instead of producing and saving the thumbnails), since that's the scope of the ticket, and that part has already been described in the grant application.

Here's how I think it ought to be. The whole thing is going to be backed by a single private S3 bucket and an arbitrary number of reverse proxies in front of it. It has to be a private S3 bucket because we can't possibly rate limit thumbnail downloads on a public bucket, which might result in some unpleasant billing surprises down the line. The proxies will let us link to the thumbnails through our own domain instead of the big raw S3 url and control rate limits. Each thumbnail will follow the naming scheme {uuid}_{max_horizontal_pixels} (ex. `99663c07-79e6-4a4f-84a2-af2978493b09_300.jpg`), which will allow us to thumbnail at multiple resolutions later if we really want to. An example URL might be https://api.creativecommons.engineering/thumbs/99663c07-79e6-4a4f-84a2-af2978493b09_300.jpg.

We will need to use a [special version of nginx](https://github.com/anomalizer/ngx_aws_auth/) that understands IAM credentials to access private buckets.

We need to have some redundancy for the thumbnail proxy because not having the thumbnails available means a bunch of broken links showing up in the search results. It would probably be prudent to reuse the API EC2 instances for this, since they're reasonably powerful instance types and we already have them set up in an autoscaling group. This would also mean we wouldn't need to allocate any additional server infrastructure.

We should put a CDN in front of the servers for better resiliency, faster global distribution, and probably lower bandwidth expenses.

Here's a diagram.
![Thumbnail arch](https://i.imgur.com/FWNBSis.jpg)

**Comment by aldenstpage** [comment]
tagging @kgodey for feedback, you can close this issue when you're done reviewing it

**Comment by kgodey** [comment]
That seems solid, @aldenstpage, I don't have any feedback.
