### ISSUE TITLE
Automatically clean up after failed indexing runs

### ISSUE THREAD

**Issue by aldenstpage** [creativecommons/cccatalog-api#402]
When an indexing job fails (such as if a node in our Elasticsearch cluster has a full disk, or a bug in indexer-worker halts the process), the incomplete index is left inside of the Elasticsearch cluster, requiring someone to manually delete it. The indexer should detect this condition when the job starts and handle it.

The production index is determined by the `image` alias. The indexer should delete any index NOT pointed to by this alias following the naming scheme `image-<uuid>`.

**Comment by hedonhermdev** [comment]
Can I work on this issue?

**Comment by CodeMonk263** [comment]
Can i work on this issue?

**Comment by kgodey** [comment]
@hedonhermdev go ahead. @CodeMonk263 please find another issue to work on since @hedonhermdev commented first.

**Comment by DantrazTrev** [comment]
@hedonhermdev are still working on this issue?

**Comment by hedonhermdev** [comment]
No.

**Comment by DantrazTrev** [comment]
Can i take it over?

**Comment by kgodey** [comment]
Go ahead @DantrazTrev

**Comment by tushar912** [comment]
@DantrazTrev are u still working on this?

**Comment by kgodey** [comment]
@tushar912 it's been a few months since @DantrazTrev's post, I think you can go ahead and work on this.

**Comment by tushar912** [comment]
Ok

**Comment by tushar912** [comment]
The way i understood this issue is as follows. The main indexing job is done by <code>indexer.py</code> in <code>ingestion_server</code> . The <code>TableIndexer</code> class contains a method <code>_index_table</code> which checks if the database is in sync with index and replicates if not.There are two methods of indexing. <code>reindex</code> which creates a new index and makes it live alias and <code>update</code> which updates the index. Currently during reindex if the index is not created successfully it still persists in the cluster so the job is to delete the index if indexing fails . @kgodey  or @aldenstpage please tell if i have understood correctly.

**Comment by tushar912** [comment]
Also i am thinking of modifying the already existing <code>consistency_check</code> method and add it to the <code>reindex</code> to delete the index if it is not indexed properly. Am i on the right track?
