### ISSUE TITLE
Implement internal thumbnailing

### ISSUE THREAD

**Issue by annatuma** [creativecommons/cccatalog-api#416]
The easiest way to do this is probably to beef up our existing thumbnail proxy (willnorris/imageproxy). Currently, we use it to ensure that every 3rd party image we display is SSL secured, but we could just proxy everything. It's also hooked up to an S3 cache already.

Resizing images dynamically is bandwidth and CPU expensive. I will have to do some testing to ensure this is feasible without investing in more hardware. We also need to make sure that the cached images are served up through our CDN.

**Comment by HAKSOAT** [comment]
Can I get more information about this? I'll like to work on it

**Comment by aldenstpage** [comment]
The easiest way to do this is probably to beef up our existing thumbnail proxy (willnorris/imageproxy). Currently, we use it to ensure that every 3rd party image we display is SSL secured, but we could just proxy everything. It's also hooked up to an S3 cache already.

Resizing images dynamically is bandwidth and CPU expensive. I will have to do some testing to ensure this is feasible without investing in more hardware. We also need to make sure that the cached images are served up through our CDN.

@kgodey tagging you since this is a bit of a shift in our original plan, but I think it's going to be a lot less work than doing the thumbnailing through scrapy-cluster.

**Comment by kgodey** [comment]
Okay, sounds good @aldenstpage. Please update the architecture in the wiki internally.

**Comment by anoited007** [comment]
@kgodey  and @aldenstpage I am not fully aware of how the existing solution that needs to be beefed up works but this can be something that using AWS Lambda can also do since you have S3 bucket already. This takes the computation away from your actual servers plus you can use caching as well.

**Comment by aldenstpage** [comment]
Lambda is one possible avenue, but we've avoided using it so far for a couple of reasons. The potential price and performance of this task on Lambda are not obvious to me, while those traits are much easier to anticipate when implemented serverside. There's also the question of portability of Lambda. Most importantly, I think it would be a lot more work to implement this particular task in Lambda than to expand the usage of our existing solution.

I've run some performance tests and feel comfortable with thumbnailing everything dynamically on our servers.
