### ISSUE TITLE
Create GitHub workflow for adding issues and PRs to appropriate project

### ISSUE THREAD

**Issue by kgodey** [creativecommons/cccatalog-api#438]
## Problem Description
Currently, we need to manually add new issues to the [CC Search backlog GitHub project](https://github.com/orgs/creativecommons/projects/10). We'd like to automate this.

## Solution Description
Set up a GitHub workflow (using GitHub Actions) to
- automatically add new issues created in this repository to the [CC Search backlog GitHub project](https://github.com/orgs/creativecommons/projects/10).
- automatically add new PRs created in this repository to the [CC Search active sprint GitHub project](https://github.com/orgs/creativecommons/projects/7).

**Bonus features** (not sure if these are possible)
- automatically move PRs created by people that are not in the `creativecommons` GitHub organization to the "In Progress (Community)" column.
- automatically move issues with linked PRs from the backlog project to the active sprint project.

## Additional context
- [GitHub Actions documentation](https://help.github.com/en/actions)

**Comment by Maxslide** [comment]
Hey, I woudl like to work on this issue.
The newly created issues in this repo must be moved to which column in the CC search backlog?

**Comment by Maxslide** [comment]
Alright, I'll try and work on this and get it resolved

**Comment by Maxslide** [comment]
This seems to be a good solution to our probelms https://github.com/philschatz/project-bot

**Comment by kgodey** [comment]
@Maxslide we want to set up a GitHub Action; we do not want alternate solutions. Please see this similar PR for an example: https://github.com/creativecommons/cccatalog-frontend/pull/710

> I found something which seems to be a very easy method to do
> https://help.github.com/en/github/managing-your-work-on-github/configuring-automation-for-project-boards

The project automation you mentioned here does not work to add issues automatically to a project or to move them between project. It only works once the issue has been added to a project.

**Comment by Maxslide** [comment]
I belive i cant check if it works, please check and ket me know if it is working, i have not added any column name as they have already been assigned as mentioned by you earlier

**Comment by Maxslide** [comment]
https://github.com/creativecommons/cccatalog-api/issues/438#issuecomment-594798627
initially i was plannign to use this for the automation, but on seeing the reference PR you mentioned, i found that to be better and hence used that

**Comment by Maxslide** [comment]
Hey, i have sent a pull request, kinfly reveiw it

**Comment by aldenstpage** [comment]
I'm reopening this because we had to revert #441.

**Comment by kgodey** [comment]
Removing the "in progress" label and assignee.

**Comment by RutujaD182** [comment]
Hey, I would like to work on this. Can I work on this?

**Comment by RutujaD182** [comment]
Hey, I would like to work on this. Can I work on this

**Comment by outloudvi** [comment]
For the bonuses:
* automatically move PRs created by people that are not in the creativecommons GitHub organization to the "In Progress (Community)" column.
    * Should be doable since we have [`/orgs/:org/members`](https://developer.github.com/v3/orgs/members/#members-list).
* automatically move issues with linked PRs from the backlog project to the active sprint project.
    * I don't think GitHub links it actively (See [here](https://api.github.com/repos/creativecommons/cccatalog-api/pulls/450) you don't find a "438"). Might be doable if we actively parse the comments in [PR](https://api.github.com/repos/creativecommons/cccatalog-api/pulls/450) and [commits](https://api.github.com/repos/creativecommons/cccatalog-api/pulls/450/commits).

**Comment by outloudvi** [comment]
I think this method will work and only work **for issues** with **a prefilled token** given with "write:org": in my [test organization](https://github.com/cc438-playground/cc438-testing/actions), it [failed](https://github.com/cc438-playground/cc438-testing/runs/500109245) with `GITHUB_TOKEN` by itself, but [worked](https://github.com/cc438-playground/cc438-testing/runs/500098575) with a pre-filled token with "read:org" and "write:org" permission. And notice that I'm the owner of my org, even this doesn't change the fact that `GITHUB_TOKEN` cannot write the organization projects (notice that it's **organization** projects). This is reasonable since an repository should not be able to write the settings of the organization.

For PR, as said in the [doc](https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets),

> You can use and read encrypted secrets in a workflow file if you have access to edit the file. 

Therefore, PRs by outside contributors cannot read your secret and is not expected to edit the organization project.

---

As a result, I would say it might not be the right way to do that with GitHub Actions for **organization projects**. Reposotiry projects might work though.

For any tests, you can try creating issues and PRs [here](https://github.com/cc438-playground/cc438-testing) to ses if it's working.

---

References:
* https://help.github.com/en/actions/configuring-and-managing-workflows/authenticating-with-the-github_token#permissions-for-the-github_token

**Comment by kgodey** [comment]
@outloudvi I've added a secret with the appropriate permissions to this repo. You can access it by using `secrets.ORG_GITHUB_TOKEN`.
