### ISSUE TITLE
Test GitHub Action

### ISSUE THREAD

**Issue by kgodey** [creativecommons/cccatalog-api#456]

**Comment by kgodey** [comment]
It works! Thanks @outloudvi and @Maxslide.

**Comment by outloudvi** [comment]
Hurray! You might want to remove PR-related part in the workflow to avoid unnecessary PR build failures.

**Comment by Maxslide** [comment]
Great!

**Comment by kgodey** [comment]
@outloudvi The PR-related part is also working. See: https://github.com/creativecommons/cccatalog-api/pull/457

It is adding it to the wrong column, though.

**Comment by outloudvi** [comment]
@kgodey As I said [here](https://github.com/creativecommons/cccatalog-api/issues/438#issuecomment-597535479), 

> You can use and read encrypted secrets in a workflow file if you have access to edit the file.

It's working just because you are a member of this organization. For outside contributors, [it would not work](https://github.com/cc438-playground/cc438-testing/pull/9) and might be confusing.

You may want to use [`continue-on-error`](https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepscontinue-on-error). See the [effect](https://github.com/cc438-playground/cc438-testing/pull/10) compared to the last one.

**Comment by kgodey** [comment]
@outloudvi right, thanks, I missed that nuance. We want PRs from members of the organization to end up in the "In Progress" column, so this is still valuable. 

We want PRs from members outside the organization to go to a different column ("In Progress (Community)") I'll see if there's a good way to do that. For now, would you be willing to send a PR that adds `continue-on-error`?

**Comment by outloudvi** [comment]
@kgodey Sure. And yes, since it's possible to check if a member is in the organization (only for those piblic members). However, I think that might need a change in the action itself, which would be more tricky than the workflow file.
