### ISSUE TITLE
Documentation for Ingestion Server

### ISSUE THREAD

**Issue by dhirensr** [creativecommons/cccatalog-api#506]
## Problem Description
Hello @aldenstpage ,
I see that currently there is no documentation for ingestion server module and it supports Falcon Api.
I would like to add documentation for the ingestion server.

## Solution Description
I would like to add swagger api spec as done in analytics module.

Once approved I would start working on it.

**Comment by aldenstpage** [comment]
I don't think we plan on extending that API. In the beginning, it looked like we were going to need an API for managing ingestion tasks on a more granular level, but it ended up not being necessary. I would like to remove some of the endpoints in the future because that API isn't especially reliable (in particular changes to the ingestion architecture have made the percent complete field in the task endpoint completely wrong). There are other places where we are more sorely in need of documentation.
