### ISSUE TITLE
The `thumbnail` key in response object of image_detail endpoint contains the source url

### ISSUE THREAD

**Issue by makkoncept** [creativecommons/cccatalog-api#541]
## Description

The `thumbnail` key in the API response of the image_detail endpoint does not contain thumbnail url but the same source url which is also there in the `url` key (eg: https://api.creativecommons.engineering/v1/images/ad1de2c1-88c0-46d1-8490-8e1c462e80a4). 

## Resolution

- [ ] I would be interested in resolving this bug.

**Comment by dhirensr** [comment]
@makkoncept : I see that the url's are different for thumbnail and url
url -> "https://images.metmuseum.org/CRDImages/is/original/DP343717.jpg",
    "thumbnail" -> "https://images.metmuseum.org/CRDImages/is/web-large/DP343717.jpg"
also the resolution for both the images are different.  I guess it's working correctly.

**Comment by makkoncept** [comment]
Oh, Thanks for the heads up. I didn't noticed the ending of the urls.

I was mostly alarmed by the fact that the API responds with two different thumbnail values for the same image on different endpoints - eg: consider the first image in https://api.creativecommons.engineering/v1/images?q=hello 
- It's thumbnail is `https://api.creativecommons.engineering/v1/thumbs/98b01826-d8d8-4598-a079-9330da4f0965` 
- It's thumbnail in its detail response(https://api.creativecommons.engineering/v1/images/98b01826-d8d8-4598-a079-9330da4f0965) is `https://live.staticflickr.com/2742/4356914605_644a2d7464_m.jpg`

**Comment by dhirensr** [comment]
@makkoncept : oh yeah,this looks like a bug now because of different sizes of image.
as far as I understood the thumbnail from https://api.creativecommons.engineering/v1/thumbs/98b01826-d8d8-4598-a079-9330da4f0965 comes from the database and is only scaled with a different width which is there in cccatalog.settings.
Also the thumbnail in detail response which points to flickr is just of a different width.
still the point I want to make is that both images are same, the only problem is dimensions which I believe is done via the settings file.

**Comment by aldenstpage** [comment]
Yes, this is a problem. The source of this issue is that the thumbnail proxying logic comes from "post processing" URLs in the search response. We don't post process detail views, so instead the thumbnail falls back to whatever is stored in the database for the `thumbnail` field, resulting in a discrepancy. 

Instead of setting the thumbnail through postprocessing, we should generate the link to the internal thumbnail through a model property [like we do with `license_url`](https://github.com/creativecommons/cccatalog-api/blob/master/cccatalog-api/cccatalog/api/models.py#L114). This will result in cleaner code and more predictable responses.

This doesn't impact CC Search because we don't display thumbnails for detail views, but it would be good to fix this confusing behaviour anyway.
