### ISSUE TITLE
Change display name of admin label for filtering content

### ISSUE THREAD

**Issue by annatuma** [creativecommons/cccatalog-api#561]
When trying to upload a provider/source logo in the Django UI for Content Provider, an SVG file was rejected. We believe this may be in error.

Separately, can we change the "filter content" label to say "hide content" for more clarity, so that we know without a doubt that this is the on/off flag for providers/sources to show on the frontend?

**Comment by aldenstpage** [comment]
This is a known issue with Django. I'll make a patch for it. We can also change the display name of filter_content easily enough.

**Comment by aldenstpage** [comment]
@annatuma, unfortunately, after educating myself on this issue a little more, I think it would be better if you worked around this problem by rasterizing the image (converting it to .png in Inkscape or other [similar application](https://apple.stackexchange.com/questions/25012/are-there-any-native-tools-for-svg-conversion-on-os-x)) before uploading it through the admin panel.

The reason that our web framework doesn't support SVG uploads is because there are some security issues with the format. If someone was able to obtain your admin credentials, it would be a possible vector for distributing malware to end users. Writing some custom SVG validation is an option for us, but if rasterization is acceptable, we should take that route instead.

I'll still change the display name of `filter_content` though, so I'm going to leave this ticket open for the time being.
