### ISSUE TITLE
EOL as a source?

### ISSUE THREAD

**Issue by aod-123** [creativecommons/cccatalog-api#590]
Sorry, this isn't really a bug but I couldn't find any information regarding EOL (Encyclopedia of Life) as a source. It's currently listed in the documentation as being one of the sources but we don't seem to be getting any results with it. I'm just wondering what the reasoning was for removing/disabling it? Will that be temporary or will it not be included going forward?

**Comment by mathemancer** [comment]
It appears we last successfully collected info from EOL (via Common Crawl Script) in April 2019.    

Sadly, they appear to have changed their URL formats since then.  I assume (but can't be certain) that someone filtered them at the DB level (i.e., set `filter_content=t` for the `eol` provider in the `content_providers` table) since we'd show nothing in the UI for them except potentially broken links.

They are part of the National Museum of Natural History, but their images appear not to be returned by the Smithsonian API.

For evidence, see the response to

https://eol.org/api/data_objects/1.0/8105579.json .  This has the data about a fish with the scientific name _Zebrasoma flavescens_.  There are many results from this query (the scientific name) in CC Search, but none if you restrict to the Smithsonian: National Museum of Natural History source:
https://ccsearch.creativecommons.org/search?q=Zebrasoma%20flavescens
https://ccsearch.creativecommons.org/search?q=Zebrasoma%20flavescens&source=smithsonian_national_museum_of_natural_history

In order to bring the EOL provider back, I think we need to either:
1. determine why the `EOL.py` script is no longer picking up new images and fix it, or
2. try to change to an API-based collection strategy.

W.r.t. (2), there a few APIs available:  https://eol.org/docs/what-is-eol/data-services .  Perhaps one of them would suffice.

**Comment by annatuma** [comment]
If their data isn't available through the Smithsonian API for NMNH, then I suggest we go with route 2. Even if we did fix the existing Common Crawl script, my assumption is we'd still get better results through a direct API integration.

We already have a ticket for this: https://github.com/creativecommons/cccatalog/issues/299

We just haven't had the bandwidth to work on this yet.
